<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Resources\logo.ico</ApplicationIcon>
    <AssemblyName>RegistroCalificaciones</AssemblyName>
    <RootNamespace>RegistroCalificaciones</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\header.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\header.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="ExcelDataReader" Version="3.7.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.7.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.6" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.6" />
    <PackageReference Include="QuestPDF" Version="2025.5.1" />
  </ItemGroup>

</Project>